### ISSUE TITLE
openvpn watchdog

### ISSUE THREAD

**Issue by romainlavisse** [j-bill/torrentbox#2]
Hi,
first thanks for your work my seedbox work really well.
i dont know where should i ask you so i do it here :
is there a way to stop download for exemple i openssh stop in order to not spot your data online ?
thanks

**Comment by j-bill** [comment]
what exactly do you mean **in order to not spot your data online**?

-------

you can stop downloads through the web interface of qbittorrent. either that or just kill the qbittorrent process. tho that can lead to corrupted files in my experience.

there is a script in here that runs every 5 minutes and checks if you're still online. if not it will restart the openvpn service. so just killing the openvpn connection will not do shit.

**Comment by romainlavisse** [comment]
_there is a script in here that runs every 5 minutes and checks if you're still online. if not it will restart the openvpn service. so just killing the openvpn connection will not do shit._
Ok this is one of the thing i would like to know the other is, if openvpn service is stop, will qbitorrent continu to dl or stop because if it continu to dl it can be annoying

**Comment by j-bill** [comment]
I've added iptables to the installation script. they stop traffic from not using the tun(VPN) network interface.

if you want to make sure it works just stop all your torrents, queue up the "Torrent Address detection" magnet link from ipleak.net and then kill your VPN with `systemctl openvpn stop`.

**Comment by romainlavisse** [comment]
ok thanks
